apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "dummy-cleaned-agg-read-{{ macros.uuid.uuid4() }}-{{ task_instance.try_number }}"
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "tese-spark:latest"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/work-dir/cenarios/cenario_od_covid/covid_pipelines/main.py"
  arguments: [
    "cleaned-and-filter-containment",
    "--source-data",
    "gs://lncc-tese-datafrag/dummy_warehouse/dummy_raw",
    "--table",
    "dummy_treated_agg",
    "--filter",
    "((A >= 6 AND A <= 8) AND ((B = 6) OR (C >= 11 AND C <= 13)))",
    "--read-datafrag",
    "{{ datafrag_config.dataflow }}"
  ]
  hadoopConf:
    "fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
  sparkConf:
    "spark.sql.shuffle.partitions": "10"
    "spark.sql.parquet.compression.codec": "gzip"
  sparkVersion: "3.2.2"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 2
    memory: "2500m"
    labels:
      version: 3.2.2
    serviceAccount: spark
    env:
    - name: WAREHOUSE
      value: "{{ env_config.warehouse }}"
    - name: CASSANDRA_HOST
      value: "{{ env_config.cassandra_host }}"
    - name: CASSANDRA_PORT
      value: "{{ env_config.cassandra_port }}"
    - name: GOOGLE_BUCKET
      value: "{{ env_config.google_bucket }}"
    - name: DATAFRAG_WAREHOUSE
      value: "{{ env_config.datafrag_warehouse }}"
    - name: DATAFRAG_METATABLE
      value: "{{ env_config.datafrag_metatable }}"
    - name: DATAFRAG_TC_METATABLE
      value: "{{ env_config.datafrag_tc_metatable }}"
    - name: DATAFRAG_KEYSPACE
      value: "{{ env_config.datafrag_keyspace }}"
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "{{ env_config.google_application_credentials }}"
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 2
    memory: "1024m"
    labels:
      version: 3.2.2
    env:
    - name: WAREHOUSE
      value: "{{ env_config.warehouse }}"
    - name: CASSANDRA_HOST
      value: "{{ env_config.cassandra_host }}"
    - name: CASSANDRA_PORT
      value: "{{ env_config.cassandra_port }}"
    - name: GOOGLE_BUCKET
      value: "{{ env_config.google_bucket }}"
    - name: DATAFRAG_WAREHOUSE
      value: "{{ env_config.datafrag_warehouse }}"
    - name: DATAFRAG_METATABLE
      value: "{{ env_config.datafrag_metatable }}"
    - name: DATAFRAG_TC_METATABLE
      value: "{{ env_config.datafrag_tc_metatable }}"
    - name: DATAFRAG_KEYSPACE
      value: "{{ env_config.datafrag_keyspace }}"
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "{{ env_config.google_application_credentials }}"
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"